# These are supported funding model platforms

# github: [linnjs]  # Uncomment and add your GitHub Sponsors username
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# custom: ['https://example.com']  # Replace with up to 4 custom sponsorship URLs
