# GitHub Labels Configuration
# These labels are used by the PR auto-labeler workflow
#
# To sync these labels with your repository, you can use:
# https://github.com/EndBug/label-sync
# or create them manually in GitHub UI
#
# Color scheme:
# - Blue/Purple: New features and enhancements
# - Red/Orange: Bugs and breaking changes
# - Teal/Cyan: Documentation and testing
# - Yellow: Refactoring and caution
# - Green: CI/CD and automation
# - Gray: Infrastructure and builds

# Type labels (based on conventional commits)
- name: enhancement
  color: '7B68EE'
  description: '✨ New feature or enhancement - adds functionality (conventional commit: feat)'

- name: bug
  color: 'DC143C'
  description: '🐛 Bug fix - resolves an issue or error (conventional commit: fix)'

- name: documentation
  color: '20B2AA'
  description: '📚 Documentation improvements - updates docs, comments, or guides (conventional commit: docs)'

- name: style
  color: 'FF69B4'
  description: '💅 Code style changes - formatting, whitespace, missing semicolons (conventional commit: style)'

- name: refactor
  color: 'FFD700'
  description: '♻️ Code refactoring - restructuring without changing behavior (conventional commit: refactor)'

- name: performance
  color: '9370DB'
  description: '⚡ Performance improvements - optimizations and speed enhancements (conventional commit: perf)'

- name: testing
  color: '48D1CC'
  description: '🧪 Test updates - adding or updating tests (conventional commit: test)'

- name: maintenance
  color: 'D2B48C'
  description: '🔧 Maintenance tasks - routine upkeep and housekeeping (conventional commit: chore)'

- name: ci/cd
  color: '228B22'
  description: '🚀 CI/CD changes - workflow automation and deployment (conventional commit: ci)'

- name: build
  color: '808080'
  description: '🏗️ Build system changes - build tools, dependencies, config (conventional commit: build)'

- name: revert
  color: '696969'
  description: '⏪ Revert changes - undoing previous commits (conventional commit: revert)'

- name: breaking change
  color: 'FF4500'
  description: '💥 BREAKING CHANGE - incompatible API changes requiring major version bump'

# Size labels (auto-added based on PR size)
- name: size/XS
  color: '00E676'
  description: '📏 Extra small change - less than 10 lines modified'

- name: size/S
  color: '76FF03'
  description: '📏 Small change - less than 50 lines modified'

- name: size/M
  color: 'FDD835'
  description: '📏 Medium change - less than 200 lines modified'

- name: size/L
  color: 'FF6D00'
  description: '📏 Large change - less than 500 lines modified'

- name: size/XL
  color: 'D50000'
  description: '📏 Extra large change - 500+ lines modified, consider splitting'

# Additional useful labels
- name: dependencies
  color: '0366D6'
  description: '📦 Dependency updates - library and package upgrades'

- name: security
  color: 'B22222'
  description: '🔒 Security fixes - patches for vulnerabilities'

- name: good first issue
  color: '7057FF'
  description: '👋 Good for newcomers - great starting point for new contributors'

- name: help wanted
  color: '008672'
  description: '🙏 Help wanted - seeking community input or assistance'

- name: priority: high
  color: 'FF0000'
  description: '🔴 High priority - needs immediate attention'

- name: priority: medium
  color: 'FFA500'
  description: '🟡 Medium priority - should be addressed soon'

- name: priority: low
  color: '00FF00'
  description: '🟢 Low priority - can be deferred'

- name: question
  color: 'BA68C8'
  description: '❓ Question - seeking clarification or discussion'

- name: wontfix
  color: 'E0E0E0'
  description: '⛔ Won\'t fix - this will not be worked on'

- name: duplicate
  color: '9E9E9E'
  description: '🔄 Duplicate - this issue or PR already exists elsewhere'

- name: invalid
  color: 'FFEB3B'
  description: '❌ Invalid - not applicable or incorrect'

- name: stale
  color: 'BDBDBD'
  description: '⏳ Stale - no recent activity, may be closed'

- name: blocked
  color: 'B71C1C'
  description: '🚫 Blocked - waiting on external dependency or decision'
